# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://felipebarbosa.me" # the base hostname & protocol for your site
# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Felipe Barbosa
  avatar: felipe_barbosa-logo-icon-alternative.png
  gravatar: # Email MD5 hash
  description: "Um blog para falar sobre Marketing, Produto e Estratégia de Negócios." # used by search engines
  author: Felipe Barbosa
  name: Felipe Barbosa
  locale: pt-br
  image: https://res.cloudinary.com/felipe-barbosa/image/upload/v1677306860/Brand%20Assets/social-image-og-alternative-b.png
  
  # Header and footer text
  header_text: >
    <h1 style="font-size: 1.6em;">Marketing & Produto & Estratégia</h1>
        
  header_text_feature_image:
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> and <a href="https://www.netlify.com/">Netlify</a><br>Felipe Barbosa 2025

  # Icons
  rss: true
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "felipecbarbosa"
  google_plus:
  instagram:
  linkedin: https://www.linkedin.com/in/felipecardosobarbosa/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  ideas: # https://portal.prodpad.com/b80a11cc-6d54-11e7-9642-22000a2145da
  cv: 
  twitter:
  medium: https://www.felipebarbosa.me/medium/
  ajuda: # https://ajuda.felipebarbosa.me/

  # Scripts
  disqus_shortname: # felipebarbosa
  search: false # Enable the search feature
    
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"
  str_download: "Faça o download do meu"
  str_ideas: "Deixe sua"
  str_ajuda: "Precisa de"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Plus+Jakarta+Sans:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "/page:num/"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-redirect-from]
